baseURL = "http://example.org/"
languageCode = "en-us"
title = "MESH"
tags = ["steam", "education", "fablab", "events", "educational", "programs"]
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[privacy]
  # Google Analytics privacy settings - https://gohugo.io/about/hugo-and-gdpr/index.html#googleanalytics
  [privacy.googleAnalytics]
    # set to true to disable service
    disable = false
    # set to true to meet General Data Protection Regulation (GDPR)
    anonymizeIP = false
    respectDoNotTrack = false
    useSessionStorage = false

[params]
  slogan = "MESH is an initiative by SokoTech"
  description = "Mesh description: Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation."
  copyright = [
    "&copy; 2019 SokoTech"
  ]

  # Nav links in the side bar
  [[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  name = "About"
  url = "about/"
  weight = 2

  [[menu.main]]
  name = "Get in touch"
  url = "contact/"
  weight = 3

# social-profiles.
  [params.social]
  facebook      = "full Social profile url in facebook"
  email         = "email@example.com"
  twitter       = "full profile url in twitter"
  linkedin      = "full profile url in linkedin"
  instagram     = "full profile url in instagram"
  github        = "full profile url in github"
